### ISSUE TITLE
jd

### ISSUE THREAD

**Issue by vitvly** [vitvly/ob-testing#13]

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0x67a80209101048d980666c47f8a7cb40b9a70a51](https://ropsten.etherscan.io/address/0x67a80209101048d980666c47f8a7cb40b9a70a51)
![QR Code](https://testing.openbounty.status.im/qr/siphiuel/ob-testing/bounty/13/6f60db41deb4c1580d0d55e346fca0411d67e864a37b88b6c2407448ebff3547/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://testing.openbounty.status.im](https://testing.openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
